# Generated by Django 5.0.7 on 2024-07-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
