# Generated by Django 5.0.7 on 2024-07-21 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_test_cases_usersubmission_delete_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
        ),
    ]
