# Generated by Django 5.0.7 on 2024-07-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_test_cases_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='problem',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
